color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.6675562039017677
  lightness: 0.014731701230630279
  saturation: 0.6705771177075803
  rhythmicContrast: 0.2503286926075816
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
name: melon
layout_spectrum: 0.08514064946211874
typography_spectrum: 0.8775258690584451
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/c0e192df-d324-41f8-9cb1-55fe8fe665ca.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/c0e192df-d324-41f8-9cb1-55fe8fe665ca.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4012145a-42f8-4cc7-9b4b-97aac3e0afee.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/10daf770-76d5-4123-9006-cdedeccafb56.jpg
title: 'Melon Investments '
description: Global Alternative Investment Opportunities
purpose:
  - type: contact
    url: 'mailto:admin@meloninvestments.org'
    label: Email us
